-- Meal Fresh — recettes de démarrage copiées dans chaque nouveau compte.
-- Généré depuis prisma/seed.ts (l'ancien seed SQLite).

insert into public.starter_recipes (title, instructions) values
  ('Crème choco', 'Mélanger le chocolat noir fondu avec le lait de soja, le sucre et la fécule de maïs. Faire épaissir à feu doux.'),
  ('Dahl lentilles', 'Faire revenir l''oignon avec le curry, ajouter les lentilles corail, le lait de coco et servir chaud avec du riz.'),
  ('Pâtes courgette curry coco', 'Cuire les pâtes. Faire poêler les courgettes avec le curry et déglacer au lait de coco.'),
  ('Gnocchis saumon', 'Poêler les gnocchis, faire saisir le saumon frais et lier le tout à la crème de soja.'),
  ('Pâtes bolognaises végé', 'Faire rissoler l''oignon et les carottes, ajouter le haché végétal et la pulpe de tomate. Servir sur les pâtes.'),
  ('Burgers végé', 'Griller le haché végétal et le pain burger. Assembler avec rondelles de tomate et fromage fondu.'),
  ('Cabillaud lait de coco', 'Pocher le filet de cabillaud dans le lait de coco parfumé au curry. Servir accompagné de riz.'),
  ('One pot chili PST', 'Mijoter les protéines de soja avec le riz, haricots rouges, maïs, pulpe de tomate, oignon rouge et paprika.'),
  ('Bagel jambon', 'Garnir le bagel avec le jambon, le fromage et des rondelles de concombre frais.'),
  ('Crêpes fromage jambon', 'Préparer la pâte avec farine, lait, œufs, huile et pincée de sucre. Garnir de jambon et fromage.'),
  ('Chakchouka', 'Faire revenir les pommes de terre et oignons au beurre, ajouter les épices et pocher les œufs par-dessus.'),
  ('Pâtes carbo', 'Faire dorér les lardons, cuire les pâtes al dente et lier le tout avec la crème de soja chaud.'),
  ('PDT et Patate douce sautées steak lentilles', 'Sauter les pommes de terre et patates douces en dés. Servir avec le steak de lentilles rissolé.'),
  ('Pâtes cheddar pulpe tomate', 'Napper les pâtes chaudes avec la sauce pulpe de tomate et faire fondre généreusement le cheddar.'),
  ('Riz soja légumes œuf', 'Sauter le riz avec poivrons, carottes, oignons, sauce soja et incorporer l''œuf brouillé.'),
  ('Salade de riz', 'Mélanger le riz froid avec dés de tomate, concombre, œufs durs et de petits dés de fromage.')
on conflict (title) do update set instructions = excluded.instructions;

insert into public.starter_recipe_ingredients (starter_recipe_id, name, category_name) values
  ((select id from public.starter_recipes where title = 'Crème choco'), 'Chocolat noir', 'Sucré'),
  ((select id from public.starter_recipes where title = 'Crème choco'), 'Lait de soja', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Crème choco'), 'Sucre', 'Sucré'),
  ((select id from public.starter_recipes where title = 'Crème choco'), 'Fécule de maïs', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Dahl lentilles'), 'Riz', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Dahl lentilles'), 'Oignon', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Dahl lentilles'), 'Lentilles corail', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Dahl lentilles'), 'Curry', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Dahl lentilles'), 'Lait de coco', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Pâtes courgette curry coco'), 'Pâtes', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Pâtes courgette curry coco'), 'Courgette', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Pâtes courgette curry coco'), 'Curry', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Pâtes courgette curry coco'), 'Lait de coco', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Gnocchis saumon'), 'Gnocchis', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Gnocchis saumon'), 'Crème soja', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Gnocchis saumon'), 'Saumon frais', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Pâtes bolognaises végé'), 'Haché végétal', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Pâtes bolognaises végé'), 'Pâtes', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Pâtes bolognaises végé'), 'Pulpe de tomate', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Pâtes bolognaises végé'), 'Carotte', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Pâtes bolognaises végé'), 'Oignon', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Burgers végé'), 'Pain burger', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Burgers végé'), 'Haché végétal', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Burgers végé'), 'Tomate', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Burgers végé'), 'Fromage', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Cabillaud lait de coco'), 'Cabillaud', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Cabillaud lait de coco'), 'Lait de coco', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Cabillaud lait de coco'), 'Curry', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Cabillaud lait de coco'), 'Riz', 'Glucides'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Protéines de soja', 'Protéines'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Riz', 'Glucides'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Paprika', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Haricots rouges', 'Glucides'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Pulpe de tomate', 'Légumes'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Maïs', 'Glucides'),
  ((select id from public.starter_recipes where title = 'One pot chili PST'), 'Oignon rouge', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Bagel jambon'), 'Pain bagel', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Bagel jambon'), 'Jambon', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Bagel jambon'), 'Fromage', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Bagel jambon'), 'Concombre', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Crêpes fromage jambon'), 'Farine', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Crêpes fromage jambon'), 'Lait', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Crêpes fromage jambon'), 'Œufs', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Crêpes fromage jambon'), 'Huile', 'Matières Grasses'),
  ((select id from public.starter_recipes where title = 'Crêpes fromage jambon'), 'Sucre', 'Sucré'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Pomme de terre', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Oignons', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Œufs', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Paprika', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Bouillon cube', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Miel', 'Sucré'),
  ((select id from public.starter_recipes where title = 'Chakchouka'), 'Beurre', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Pâtes carbo'), 'Lardons', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Pâtes carbo'), 'Crème soja', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Pâtes carbo'), 'Pâtes', 'Glucides'),
  ((select id from public.starter_recipes where title = 'PDT et Patate douce sautées steak lentilles'), 'Pomme de terre', 'Glucides'),
  ((select id from public.starter_recipes where title = 'PDT et Patate douce sautées steak lentilles'), 'Patate douce', 'Glucides'),
  ((select id from public.starter_recipes where title = 'PDT et Patate douce sautées steak lentilles'), 'Steak de lentilles', 'Protéines'),
  ((select id from public.starter_recipes where title = 'PDT et Patate douce sautées steak lentilles'), 'Lentilles', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Pâtes cheddar pulpe tomate'), 'Pâtes', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Pâtes cheddar pulpe tomate'), 'Cheddar', 'Produits Laitiers'),
  ((select id from public.starter_recipes where title = 'Pâtes cheddar pulpe tomate'), 'Pulpe de tomate', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Riz', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Poivron', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Oignon', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Carotte', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Sauce soja', 'Épices & Condiments'),
  ((select id from public.starter_recipes where title = 'Riz soja légumes œuf'), 'Œuf', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Salade de riz'), 'Tomate', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Salade de riz'), 'Concombre', 'Légumes'),
  ((select id from public.starter_recipes where title = 'Salade de riz'), 'Riz', 'Glucides'),
  ((select id from public.starter_recipes where title = 'Salade de riz'), 'Œuf', 'Protéines'),
  ((select id from public.starter_recipes where title = 'Salade de riz'), 'Fromage', 'Produits Laitiers')
on conflict do nothing;
