-- Meal Fresh — banque de recettes de démarrage étendue (1/3 : les recettes).
--
-- 60 recettes ajoutées aux 16 d'origine : matin, salades, soupes, féculents,
-- plats du monde, poissons, viandes, végétarien, desserts.

insert into public.starter_recipes (title, instructions) values
  ('Porridge banane cannelle', 'Faire gonfler les flocons d''avoine dans le lait chaud 5 minutes. Ajouter la banane écrasée, la cannelle et un filet de miel.'),
  ('Pain perdu', 'Battre les œufs avec le lait et le sucre. Y tremper les tranches de pain rassis puis les dorer au beurre à la poêle.'),
  ('Œufs brouillés ciboulette', 'Battre les œufs, les cuire à feu très doux en remuant sans arrêt. Retirer du feu encore crémeux et parsemer de ciboulette.'),
  ('Smoothie bowl fruits rouges', 'Mixer les fruits rouges surgelés avec le yaourt et la banane. Verser en bol et garnir de flocons d''avoine.'),
  ('Tartines avocat œuf poché', 'Écraser l''avocat sur le pain grillé. Pocher l''œuf 3 minutes dans l''eau frémissante vinaigrée et le déposer dessus.'),
  ('Granola maison', 'Mélanger flocons, amandes, miel et huile. Étaler sur une plaque et enfourner 20 minutes à 160 °C en remuant à mi-cuisson.'),
  ('Salade César poulet', 'Griller le poulet et le trancher. Mélanger la salade, les croûtons et le parmesan, puis napper de sauce césar.'),
  ('Taboulé libanais', 'Faire gonfler le boulgour. Ajouter beaucoup de persil ciselé, les dés de tomate, le jus de citron et l''huile d''olive.'),
  ('Salade grecque', 'Mélanger les gros dés de tomate et concombre avec l''oignon rouge et les olives. Couronner de feta et arroser d''huile d''olive.'),
  ('Salade de lentilles feta', 'Cuire les lentilles 20 minutes puis les rafraîchir. Ajouter l''échalote, la feta émiettée et une vinaigrette moutardée.'),
  ('Salade quinoa avocat', 'Cuire le quinoa et le laisser refroidir. Ajouter l''avocat en dés, le maïs, les tomates cerises et le jus de citron.'),
  ('Wrap poulet crudités', 'Tartiner la tortilla de fromage frais, garnir de poulet grillé, salade et carotte râpée, puis rouler serré.'),
  ('Soupe à l''oignon gratinée', 'Faire compoter les oignons émincés 30 minutes au beurre. Mouiller au bouillon, verser en bols et gratiner avec le pain et le fromage.'),
  ('Velouté de potiron', 'Cuire le potiron et la pomme de terre dans le bouillon 25 minutes. Mixer finement et détendre à la crème.'),
  ('Soupe de légumes d''hiver', 'Couper tous les légumes en morceaux, couvrir de bouillon et laisser mijoter 30 minutes. Mixer ou servir en morceaux.'),
  ('Soupe thaï coco crevettes', 'Chauffer le lait de coco avec le curry et le gingembre. Ajouter les crevettes et les champignons, cuire 5 minutes.'),
  ('Minestrone', 'Faire suer les légumes en petits dés, mouiller au bouillon et à la pulpe de tomate. Ajouter les pâtes et les haricots en fin de cuisson.'),
  ('Pâtes pesto tomates cerises', 'Cuire les pâtes al dente. Les mélanger hors du feu au pesto, aux tomates cerises coupées et aux pignons.'),
  ('Risotto aux champignons', 'Nacrer le riz, mouiller louche par louche au bouillon chaud en remuant 18 minutes. Incorporer champignons poêlés, beurre et parmesan.'),
  ('Lasagnes végétariennes', 'Alterner plaques de lasagne, sauce tomate aux légumes et béchamel. Terminer par le fromage et enfourner 35 minutes à 180 °C.'),
  ('Gratin dauphinois', 'Trancher finement les pommes de terre, les ranger en couches avec l''ail et la crème. Cuire 1 heure à 160 °C.'),
  ('Riz cantonais', 'Sauter le riz froid à feu vif avec les petits pois, le jambon en dés et l''omelette coupée en lanières. Déglacer à la sauce soja.'),
  ('Nouilles sautées au bœuf', 'Saisir les lanières de bœuf à feu vif, réserver. Sauter poivron et oignon, remettre la viande avec les nouilles et la sauce soja.'),
  ('Gnocchis à la crème de courge', 'Rôtir la courge puis la mixer avec la crème. Poêler les gnocchis et les enrober de cette crème parfumée à la sauge.'),
  ('Couscous végétarien', 'Mijoter pois chiches, carottes, courgettes et navets dans un bouillon épicé. Servir sur la semoule gonflée.'),
  ('Chili sin carne', 'Faire revenir oignon et poivron, ajouter haricots rouges, maïs, pulpe de tomate et cumin. Laisser mijoter 30 minutes.'),
  ('Curry de pois chiches épinards', 'Faire revenir l''oignon avec les épices, ajouter les pois chiches et le lait de coco. Incorporer les épinards en fin de cuisson.'),
  ('Poulet tikka masala', 'Mariner le poulet au yaourt et aux épices, le saisir puis le mijoter dans la sauce tomate crémée 20 minutes.'),
  ('Pad thaï aux crevettes', 'Réhydrater les nouilles de riz. Les sauter avec les crevettes, l''œuf brouillé et la sauce, puis parsemer de cacahuètes.'),
  ('Tacos de bœuf haché', 'Rissoler le bœuf haché avec les épices. Garnir les tortillas de viande, salade, tomate et fromage râpé.'),
  ('Ratatouille', 'Cuire séparément aubergine, courgette et poivron, puis les réunir avec la tomate et les herbes. Mijoter 40 minutes à couvert.'),
  ('Moussaka', 'Alterner tranches d''aubergine grillées et hachis à la tomate. Recouvrir de béchamel et gratiner 40 minutes.'),
  ('Tortilla espagnole', 'Confire les pommes de terre et l''oignon à l''huile. Les mêler aux œufs battus et cuire la galette à feu doux des deux côtés.'),
  ('Bo bun végétarien', 'Dresser les vermicelles froids avec crudités, tofu croustillant et herbes. Arroser de sauce sucrée-salée au citron.'),
  ('Chakchouka verte aux épinards', 'Faire tomber les épinards avec l''ail et le cumin, creuser des puits et y pocher les œufs à couvert 6 minutes.'),
  ('Saumon rôti au miel', 'Badigeonner le pavé de saumon d''un mélange miel-sauce soja. Enfourner 12 minutes à 200 °C en arrosant à mi-cuisson.'),
  ('Papillote de cabillaud aux légumes', 'Déposer le cabillaud sur un lit de julienne de légumes, citronner, fermer la papillote et cuire 20 minutes à 180 °C.'),
  ('Thon à la provençale', 'Saisir les steaks de thon 2 minutes par face. Les servir sur une compotée de tomates, olives et ail.'),
  ('Poêlée de crevettes à l''ail', 'Saisir les crevettes à l''huile d''olive avec l''ail et le persil 4 minutes. Déglacer au citron et servir aussitôt.'),
  ('Brandade de morue rapide', 'Écraser le cabillaud cuit avec la purée de pommes de terre, l''ail et l''huile d''olive. Gratiner 15 minutes.'),
  ('Poulet rôti au citron', 'Glisser le citron et le thym dans le poulet, l''enfourner 1 h 15 à 190 °C en l''arrosant régulièrement de son jus.'),
  ('Blanquette de volaille', 'Pocher le poulet avec carotte et oignon 40 minutes. Lier le bouillon au roux et à la crème, remettre la viande et les champignons.'),
  ('Poulet basquaise', 'Dorer les morceaux de poulet, les mijoter 40 minutes avec poivrons, oignons, tomate et piment d''Espelette.'),
  ('Boulettes de bœuf sauce tomate', 'Façonner les boulettes avec l''œuf et la chapelure, les dorer puis les mijoter 20 minutes dans la sauce tomate.'),
  ('Sauté de porc au caramel', 'Colorer les dés de porc, ajouter sucre et sauce soja et laisser caraméliser 25 minutes à feu doux.'),
  ('Buddha bowl quinoa', 'Disposer en secteurs le quinoa, les pois chiches rôtis, l''avocat et la carotte râpée. Napper de sauce au yaourt citronnée.'),
  ('Falafels au four', 'Mixer pois chiches, oignon, ail et herbes. Former des boulettes, les huiler et enfourner 25 minutes à 200 °C.'),
  ('Galettes de lentilles', 'Écraser les lentilles cuites avec l''œuf, la farine et les épices. Former des galettes et les dorer 4 minutes par face.'),
  ('Tofu croustillant sauce soja', 'Presser le tofu, l''enrober de fécule et le saisir jusqu''à ce qu''il croustille. Glacer à la sauce soja et au miel.'),
  ('Gratin de courgettes au chèvre', 'Poêler les rondelles de courgette, les disposer en plat avec le chèvre et la crème. Gratiner 25 minutes à 180 °C.'),
  ('Poivrons farcis au riz', 'Farcir les demi-poivrons du riz mêlé aux légumes et aux herbes. Enfourner 40 minutes à 180 °C avec un fond d''eau.'),
  ('Curry de patate douce', 'Faire revenir l''oignon et les épices, ajouter la patate douce en cubes et le lait de coco. Mijoter 25 minutes.'),
  ('Crêpes sucrées', 'Fouetter farine, œufs, lait et sucre en pâte lisse. Laisser reposer 30 minutes puis cuire les crêpes à la poêle beurrée.'),
  ('Gâteau au yaourt', 'Mélanger yaourt, sucre, œufs, farine et huile au pot. Enfourner 35 minutes à 180 °C.'),
  ('Moelleux au chocolat', 'Faire fondre chocolat et beurre, incorporer sucre, œufs puis farine. Cuire 12 minutes à 180 °C pour garder le cœur coulant.'),
  ('Compote pomme cannelle', 'Cuire les pommes en morceaux avec un fond d''eau et la cannelle 20 minutes. Écraser à la fourchette.'),
  ('Riz au lait vanillé', 'Cuire le riz rond dans le lait sucré à feu très doux 35 minutes en remuant souvent, jusqu''à consistance crémeuse.'),
  ('Cookies chocolat', 'Crémer beurre et sucre, ajouter l''œuf puis la farine et les pépites. Cuire 11 minutes à 180 °C, les cookies restent mous.'),
  ('Salade de fruits frais', 'Détailler tous les fruits en morceaux réguliers. Arroser de jus de citron et de miel, réserver 1 heure au frais.'),
  ('Banana bread', 'Écraser les bananes très mûres, mêler au sucre, aux œufs, au beurre fondu et à la farine. Cuire 50 minutes à 170 °C.')
on conflict (title) do update set instructions = excluded.instructions;
