-- Meal Fresh — banque de recettes de démarrage étendue (2/3 : les ingrédients).

insert into public.starter_recipe_ingredients (starter_recipe_id, name, category_name, quantity)
select sr.id, v.name, v.category_name, v.quantity
from (values
  ('Porridge banane cannelle', 'Flocons d''avoine', 'Glucides', '60 g'),
  ('Porridge banane cannelle', 'Lait', 'Produits Laitiers', '25 cl'),
  ('Porridge banane cannelle', 'Banane', 'Fruits', '1'),
  ('Porridge banane cannelle', 'Cannelle', 'Épices & Condiments', '1 pincée'),
  ('Porridge banane cannelle', 'Miel', 'Sucré', '1 c. à café'),
  ('Pain perdu', 'Pain de mie', 'Glucides', '4 tranches'),
  ('Pain perdu', 'Œuf', 'Protéines', '2'),
  ('Pain perdu', 'Lait', 'Produits Laitiers', '20 cl'),
  ('Pain perdu', 'Sucre', 'Sucré', '2 c. à soupe'),
  ('Pain perdu', 'Beurre', 'Produits Laitiers', '20 g'),
  ('Œufs brouillés ciboulette', 'Œuf', 'Protéines', '3'),
  ('Œufs brouillés ciboulette', 'Beurre', 'Produits Laitiers', '15 g'),
  ('Œufs brouillés ciboulette', 'Ciboulette', 'Épices & Condiments', '1 c. à soupe'),
  ('Œufs brouillés ciboulette', 'Pain de mie', 'Glucides', '2 tranches'),
  ('Smoothie bowl fruits rouges', 'Fruits rouges', 'Fruits', '150 g'),
  ('Smoothie bowl fruits rouges', 'Yaourt nature', 'Produits Laitiers', '1'),
  ('Smoothie bowl fruits rouges', 'Banane', 'Fruits', '1'),
  ('Smoothie bowl fruits rouges', 'Flocons d''avoine', 'Glucides', '2 c. à soupe'),
  ('Smoothie bowl fruits rouges', 'Miel', 'Sucré', '1 c. à café'),
  ('Tartines avocat œuf poché', 'Pain complet', 'Glucides', '2 tranches'),
  ('Tartines avocat œuf poché', 'Avocat', 'Légumes', '1'),
  ('Tartines avocat œuf poché', 'Œuf', 'Protéines', '2'),
  ('Tartines avocat œuf poché', 'Citron', 'Fruits', '1/2'),
  ('Tartines avocat œuf poché', 'Paprika', 'Épices & Condiments', '1 pincée'),
  ('Granola maison', 'Flocons d''avoine', 'Glucides', '300 g'),
  ('Granola maison', 'Amandes', 'Protéines', '100 g'),
  ('Granola maison', 'Miel', 'Sucré', '80 g'),
  ('Granola maison', 'Huile', 'Matières Grasses', '3 c. à soupe'),
  ('Granola maison', 'Cannelle', 'Épices & Condiments', '1 c. à café'),
  ('Salade César poulet', 'Blanc de poulet', 'Protéines', '2'),
  ('Salade César poulet', 'Salade verte', 'Légumes', '1'),
  ('Salade César poulet', 'Parmesan', 'Produits Laitiers', '50 g'),
  ('Salade César poulet', 'Pain complet', 'Glucides', '2 tranches'),
  ('Salade César poulet', 'Moutarde', 'Épices & Condiments', '1 c. à café'),
  ('Taboulé libanais', 'Boulgour', 'Glucides', '150 g'),
  ('Taboulé libanais', 'Persil', 'Épices & Condiments', '1 bouquet'),
  ('Taboulé libanais', 'Tomate', 'Légumes', '3'),
  ('Taboulé libanais', 'Citron', 'Fruits', '2'),
  ('Taboulé libanais', 'Huile d''olive', 'Matières Grasses', '4 c. à soupe'),
  ('Salade grecque', 'Tomate', 'Légumes', '4'),
  ('Salade grecque', 'Concombre', 'Légumes', '1'),
  ('Salade grecque', 'Feta', 'Produits Laitiers', '150 g'),
  ('Salade grecque', 'Olives', 'Matières Grasses', '100 g'),
  ('Salade grecque', 'Oignon rouge', 'Légumes', '1'),
  ('Salade grecque', 'Huile d''olive', 'Matières Grasses', '3 c. à soupe'),
  ('Salade de lentilles feta', 'Lentilles', 'Glucides', '200 g'),
  ('Salade de lentilles feta', 'Feta', 'Produits Laitiers', '100 g'),
  ('Salade de lentilles feta', 'Échalote', 'Légumes', '1'),
  ('Salade de lentilles feta', 'Moutarde', 'Épices & Condiments', '1 c. à café'),
  ('Salade de lentilles feta', 'Huile d''olive', 'Matières Grasses', '3 c. à soupe'),
  ('Salade quinoa avocat', 'Quinoa', 'Glucides', '150 g'),
  ('Salade quinoa avocat', 'Avocat', 'Légumes', '1'),
  ('Salade quinoa avocat', 'Maïs', 'Glucides', '150 g'),
  ('Salade quinoa avocat', 'Tomate', 'Légumes', '2'),
  ('Salade quinoa avocat', 'Citron', 'Fruits', '1'),
  ('Wrap poulet crudités', 'Tortilla', 'Glucides', '2'),
  ('Wrap poulet crudités', 'Blanc de poulet', 'Protéines', '1'),
  ('Wrap poulet crudités', 'Salade verte', 'Légumes', 'quelques feuilles'),
  ('Wrap poulet crudités', 'Carotte', 'Légumes', '1'),
  ('Wrap poulet crudités', 'Fromage frais', 'Produits Laitiers', '2 c. à soupe'),
  ('Soupe à l''oignon gratinée', 'Oignon', 'Légumes', '6'),
  ('Soupe à l''oignon gratinée', 'Beurre', 'Produits Laitiers', '30 g'),
  ('Soupe à l''oignon gratinée', 'Bouillon cube', 'Épices & Condiments', '1'),
  ('Soupe à l''oignon gratinée', 'Pain complet', 'Glucides', '4 tranches'),
  ('Soupe à l''oignon gratinée', 'Fromage', 'Produits Laitiers', '100 g'),
  ('Velouté de potiron', 'Potiron', 'Légumes', '800 g'),
  ('Velouté de potiron', 'Pomme de terre', 'Glucides', '2'),
  ('Velouté de potiron', 'Bouillon cube', 'Épices & Condiments', '1'),
  ('Velouté de potiron', 'Crème soja', 'Produits Laitiers', '10 cl'),
  ('Velouté de potiron', 'Muscade', 'Épices & Condiments', '1 pincée'),
  ('Soupe de légumes d''hiver', 'Poireau', 'Légumes', '2'),
  ('Soupe de légumes d''hiver', 'Carotte', 'Légumes', '3'),
  ('Soupe de légumes d''hiver', 'Pomme de terre', 'Glucides', '3'),
  ('Soupe de légumes d''hiver', 'Navet', 'Légumes', '1'),
  ('Soupe de légumes d''hiver', 'Bouillon cube', 'Épices & Condiments', '1'),
  ('Soupe thaï coco crevettes', 'Lait de coco', 'Produits Laitiers', '40 cl'),
  ('Soupe thaï coco crevettes', 'Crevettes', 'Protéines', '200 g'),
  ('Soupe thaï coco crevettes', 'Champignons', 'Légumes', '150 g'),
  ('Soupe thaï coco crevettes', 'Curry', 'Épices & Condiments', '1 c. à café'),
  ('Soupe thaï coco crevettes', 'Gingembre', 'Épices & Condiments', '1 morceau'),
  ('Soupe thaï coco crevettes', 'Citron', 'Fruits', '1'),
  ('Minestrone', 'Carotte', 'Légumes', '2'),
  ('Minestrone', 'Courgette', 'Légumes', '1'),
  ('Minestrone', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Minestrone', 'Pâtes', 'Glucides', '100 g'),
  ('Minestrone', 'Haricots rouges', 'Glucides', '200 g'),
  ('Minestrone', 'Bouillon cube', 'Épices & Condiments', '1'),
  ('Pâtes pesto tomates cerises', 'Pâtes', 'Glucides', '300 g'),
  ('Pâtes pesto tomates cerises', 'Pesto', 'Épices & Condiments', '4 c. à soupe'),
  ('Pâtes pesto tomates cerises', 'Tomate', 'Légumes', '200 g'),
  ('Pâtes pesto tomates cerises', 'Parmesan', 'Produits Laitiers', '40 g'),
  ('Risotto aux champignons', 'Riz', 'Glucides', '300 g'),
  ('Risotto aux champignons', 'Champignons', 'Légumes', '300 g'),
  ('Risotto aux champignons', 'Bouillon cube', 'Épices & Condiments', '1'),
  ('Risotto aux champignons', 'Parmesan', 'Produits Laitiers', '60 g'),
  ('Risotto aux champignons', 'Beurre', 'Produits Laitiers', '30 g'),
  ('Risotto aux champignons', 'Oignon', 'Légumes', '1'),
  ('Lasagnes végétariennes', 'Pâtes', 'Glucides', '12 plaques'),
  ('Lasagnes végétariennes', 'Courgette', 'Légumes', '2'),
  ('Lasagnes végétariennes', 'Pulpe de tomate', 'Légumes', '500 g'),
  ('Lasagnes végétariennes', 'Lait', 'Produits Laitiers', '50 cl'),
  ('Lasagnes végétariennes', 'Farine', 'Glucides', '50 g'),
  ('Lasagnes végétariennes', 'Fromage', 'Produits Laitiers', '150 g'),
  ('Gratin dauphinois', 'Pomme de terre', 'Glucides', '1 kg'),
  ('Gratin dauphinois', 'Crème soja', 'Produits Laitiers', '40 cl'),
  ('Gratin dauphinois', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Gratin dauphinois', 'Muscade', 'Épices & Condiments', '1 pincée'),
  ('Gratin dauphinois', 'Fromage', 'Produits Laitiers', '100 g'),
  ('Riz cantonais', 'Riz', 'Glucides', '300 g'),
  ('Riz cantonais', 'Petits pois', 'Légumes', '150 g'),
  ('Riz cantonais', 'Jambon', 'Protéines', '150 g'),
  ('Riz cantonais', 'Œuf', 'Protéines', '2'),
  ('Riz cantonais', 'Sauce soja', 'Épices & Condiments', '2 c. à soupe'),
  ('Nouilles sautées au bœuf', 'Nouilles', 'Glucides', '250 g'),
  ('Nouilles sautées au bœuf', 'Bœuf', 'Protéines', '300 g'),
  ('Nouilles sautées au bœuf', 'Poivron', 'Légumes', '1'),
  ('Nouilles sautées au bœuf', 'Oignon', 'Légumes', '1'),
  ('Nouilles sautées au bœuf', 'Sauce soja', 'Épices & Condiments', '3 c. à soupe'),
  ('Nouilles sautées au bœuf', 'Gingembre', 'Épices & Condiments', '1 morceau'),
  ('Gnocchis à la crème de courge', 'Gnocchis', 'Glucides', '500 g'),
  ('Gnocchis à la crème de courge', 'Potiron', 'Légumes', '400 g'),
  ('Gnocchis à la crème de courge', 'Crème soja', 'Produits Laitiers', '20 cl'),
  ('Gnocchis à la crème de courge', 'Parmesan', 'Produits Laitiers', '40 g'),
  ('Gnocchis à la crème de courge', 'Muscade', 'Épices & Condiments', '1 pincée'),
  ('Couscous végétarien', 'Semoule', 'Glucides', '300 g'),
  ('Couscous végétarien', 'Pois chiches', 'Protéines', '400 g'),
  ('Couscous végétarien', 'Carotte', 'Légumes', '3'),
  ('Couscous végétarien', 'Courgette', 'Légumes', '2'),
  ('Couscous végétarien', 'Navet', 'Légumes', '2'),
  ('Couscous végétarien', 'Ras el hanout', 'Épices & Condiments', '2 c. à café'),
  ('Chili sin carne', 'Haricots rouges', 'Glucides', '400 g'),
  ('Chili sin carne', 'Maïs', 'Glucides', '200 g'),
  ('Chili sin carne', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Chili sin carne', 'Poivron', 'Légumes', '1'),
  ('Chili sin carne', 'Oignon', 'Légumes', '1'),
  ('Chili sin carne', 'Cumin', 'Épices & Condiments', '1 c. à café'),
  ('Curry de pois chiches épinards', 'Pois chiches', 'Protéines', '400 g'),
  ('Curry de pois chiches épinards', 'Épinards', 'Légumes', '200 g'),
  ('Curry de pois chiches épinards', 'Lait de coco', 'Produits Laitiers', '40 cl'),
  ('Curry de pois chiches épinards', 'Curry', 'Épices & Condiments', '2 c. à café'),
  ('Curry de pois chiches épinards', 'Oignon', 'Légumes', '1'),
  ('Curry de pois chiches épinards', 'Riz', 'Glucides', '250 g'),
  ('Poulet tikka masala', 'Blanc de poulet', 'Protéines', '500 g'),
  ('Poulet tikka masala', 'Yaourt nature', 'Produits Laitiers', '2'),
  ('Poulet tikka masala', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Poulet tikka masala', 'Crème soja', 'Produits Laitiers', '10 cl'),
  ('Poulet tikka masala', 'Ras el hanout', 'Épices & Condiments', '2 c. à café'),
  ('Poulet tikka masala', 'Riz', 'Glucides', '250 g'),
  ('Pad thaï aux crevettes', 'Nouilles', 'Glucides', '250 g'),
  ('Pad thaï aux crevettes', 'Crevettes', 'Protéines', '250 g'),
  ('Pad thaï aux crevettes', 'Œuf', 'Protéines', '2'),
  ('Pad thaï aux crevettes', 'Cacahuètes', 'Protéines', '50 g'),
  ('Pad thaï aux crevettes', 'Sauce soja', 'Épices & Condiments', '3 c. à soupe'),
  ('Pad thaï aux crevettes', 'Citron', 'Fruits', '1'),
  ('Tacos de bœuf haché', 'Tortilla', 'Glucides', '6'),
  ('Tacos de bœuf haché', 'Bœuf', 'Protéines', '400 g'),
  ('Tacos de bœuf haché', 'Salade verte', 'Légumes', 'quelques feuilles'),
  ('Tacos de bœuf haché', 'Tomate', 'Légumes', '2'),
  ('Tacos de bœuf haché', 'Fromage', 'Produits Laitiers', '100 g'),
  ('Tacos de bœuf haché', 'Paprika', 'Épices & Condiments', '1 c. à café'),
  ('Ratatouille', 'Aubergine', 'Légumes', '1'),
  ('Ratatouille', 'Courgette', 'Légumes', '2'),
  ('Ratatouille', 'Poivron', 'Légumes', '2'),
  ('Ratatouille', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Ratatouille', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Ratatouille', 'Huile d''olive', 'Matières Grasses', '4 c. à soupe'),
  ('Moussaka', 'Aubergine', 'Légumes', '3'),
  ('Moussaka', 'Haché végétal', 'Protéines', '400 g'),
  ('Moussaka', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Moussaka', 'Lait', 'Produits Laitiers', '50 cl'),
  ('Moussaka', 'Farine', 'Glucides', '50 g'),
  ('Moussaka', 'Cannelle', 'Épices & Condiments', '1 pincée'),
  ('Tortilla espagnole', 'Pomme de terre', 'Glucides', '600 g'),
  ('Tortilla espagnole', 'Œuf', 'Protéines', '6'),
  ('Tortilla espagnole', 'Oignon', 'Légumes', '1'),
  ('Tortilla espagnole', 'Huile d''olive', 'Matières Grasses', '10 cl'),
  ('Bo bun végétarien', 'Nouilles', 'Glucides', '200 g'),
  ('Bo bun végétarien', 'Tofu', 'Protéines', '200 g'),
  ('Bo bun végétarien', 'Carotte', 'Légumes', '2'),
  ('Bo bun végétarien', 'Concombre', 'Légumes', '1'),
  ('Bo bun végétarien', 'Cacahuètes', 'Protéines', '40 g'),
  ('Bo bun végétarien', 'Sauce soja', 'Épices & Condiments', '3 c. à soupe'),
  ('Chakchouka verte aux épinards', 'Épinards', 'Légumes', '500 g'),
  ('Chakchouka verte aux épinards', 'Œuf', 'Protéines', '4'),
  ('Chakchouka verte aux épinards', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Chakchouka verte aux épinards', 'Cumin', 'Épices & Condiments', '1 c. à café'),
  ('Chakchouka verte aux épinards', 'Feta', 'Produits Laitiers', '80 g'),
  ('Saumon rôti au miel', 'Saumon frais', 'Protéines', '4 pavés'),
  ('Saumon rôti au miel', 'Miel', 'Sucré', '2 c. à soupe'),
  ('Saumon rôti au miel', 'Sauce soja', 'Épices & Condiments', '2 c. à soupe'),
  ('Saumon rôti au miel', 'Citron', 'Fruits', '1'),
  ('Saumon rôti au miel', 'Riz', 'Glucides', '250 g'),
  ('Papillote de cabillaud aux légumes', 'Cabillaud', 'Protéines', '4 filets'),
  ('Papillote de cabillaud aux légumes', 'Carotte', 'Légumes', '2'),
  ('Papillote de cabillaud aux légumes', 'Courgette', 'Légumes', '1'),
  ('Papillote de cabillaud aux légumes', 'Citron', 'Fruits', '1'),
  ('Papillote de cabillaud aux légumes', 'Huile d''olive', 'Matières Grasses', '2 c. à soupe'),
  ('Thon à la provençale', 'Thon', 'Protéines', '4 steaks'),
  ('Thon à la provençale', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Thon à la provençale', 'Olives', 'Matières Grasses', '80 g'),
  ('Thon à la provençale', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Thon à la provençale', 'Huile d''olive', 'Matières Grasses', '3 c. à soupe'),
  ('Poêlée de crevettes à l''ail', 'Crevettes', 'Protéines', '400 g'),
  ('Poêlée de crevettes à l''ail', 'Ail', 'Épices & Condiments', '3 gousses'),
  ('Poêlée de crevettes à l''ail', 'Persil', 'Épices & Condiments', '1 bouquet'),
  ('Poêlée de crevettes à l''ail', 'Citron', 'Fruits', '1'),
  ('Poêlée de crevettes à l''ail', 'Huile d''olive', 'Matières Grasses', '3 c. à soupe'),
  ('Brandade de morue rapide', 'Cabillaud', 'Protéines', '500 g'),
  ('Brandade de morue rapide', 'Pomme de terre', 'Glucides', '600 g'),
  ('Brandade de morue rapide', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Brandade de morue rapide', 'Huile d''olive', 'Matières Grasses', '5 c. à soupe'),
  ('Brandade de morue rapide', 'Lait', 'Produits Laitiers', '10 cl'),
  ('Poulet rôti au citron', 'Poulet', 'Protéines', '1'),
  ('Poulet rôti au citron', 'Citron', 'Fruits', '2'),
  ('Poulet rôti au citron', 'Pomme de terre', 'Glucides', '800 g'),
  ('Poulet rôti au citron', 'Ail', 'Épices & Condiments', '4 gousses'),
  ('Poulet rôti au citron', 'Huile d''olive', 'Matières Grasses', '3 c. à soupe'),
  ('Blanquette de volaille', 'Blanc de poulet', 'Protéines', '600 g'),
  ('Blanquette de volaille', 'Champignons', 'Légumes', '250 g'),
  ('Blanquette de volaille', 'Carotte', 'Légumes', '3'),
  ('Blanquette de volaille', 'Crème soja', 'Produits Laitiers', '20 cl'),
  ('Blanquette de volaille', 'Farine', 'Glucides', '40 g'),
  ('Blanquette de volaille', 'Riz', 'Glucides', '250 g'),
  ('Poulet basquaise', 'Poulet', 'Protéines', '1'),
  ('Poulet basquaise', 'Poivron', 'Légumes', '3'),
  ('Poulet basquaise', 'Oignon', 'Légumes', '2'),
  ('Poulet basquaise', 'Pulpe de tomate', 'Légumes', '400 g'),
  ('Poulet basquaise', 'Paprika', 'Épices & Condiments', '1 c. à café'),
  ('Poulet basquaise', 'Riz', 'Glucides', '250 g'),
  ('Boulettes de bœuf sauce tomate', 'Bœuf', 'Protéines', '500 g'),
  ('Boulettes de bœuf sauce tomate', 'Œuf', 'Protéines', '1'),
  ('Boulettes de bœuf sauce tomate', 'Pulpe de tomate', 'Légumes', '500 g'),
  ('Boulettes de bœuf sauce tomate', 'Oignon', 'Légumes', '1'),
  ('Boulettes de bœuf sauce tomate', 'Pâtes', 'Glucides', '300 g'),
  ('Sauté de porc au caramel', 'Porc', 'Protéines', '600 g'),
  ('Sauté de porc au caramel', 'Sauce soja', 'Épices & Condiments', '4 c. à soupe'),
  ('Sauté de porc au caramel', 'Sucre', 'Sucré', '2 c. à soupe'),
  ('Sauté de porc au caramel', 'Gingembre', 'Épices & Condiments', '1 morceau'),
  ('Sauté de porc au caramel', 'Riz', 'Glucides', '250 g'),
  ('Buddha bowl quinoa', 'Quinoa', 'Glucides', '200 g'),
  ('Buddha bowl quinoa', 'Pois chiches', 'Protéines', '300 g'),
  ('Buddha bowl quinoa', 'Avocat', 'Légumes', '1'),
  ('Buddha bowl quinoa', 'Carotte', 'Légumes', '2'),
  ('Buddha bowl quinoa', 'Yaourt nature', 'Produits Laitiers', '1'),
  ('Buddha bowl quinoa', 'Citron', 'Fruits', '1'),
  ('Falafels au four', 'Pois chiches', 'Protéines', '400 g'),
  ('Falafels au four', 'Oignon', 'Légumes', '1'),
  ('Falafels au four', 'Ail', 'Épices & Condiments', '2 gousses'),
  ('Falafels au four', 'Persil', 'Épices & Condiments', '1 bouquet'),
  ('Falafels au four', 'Cumin', 'Épices & Condiments', '1 c. à café'),
  ('Falafels au four', 'Farine', 'Glucides', '2 c. à soupe'),
  ('Galettes de lentilles', 'Lentilles', 'Glucides', '250 g'),
  ('Galettes de lentilles', 'Œuf', 'Protéines', '1'),
  ('Galettes de lentilles', 'Farine', 'Glucides', '3 c. à soupe'),
  ('Galettes de lentilles', 'Oignon', 'Légumes', '1'),
  ('Galettes de lentilles', 'Cumin', 'Épices & Condiments', '1 c. à café'),
  ('Tofu croustillant sauce soja', 'Tofu', 'Protéines', '400 g'),
  ('Tofu croustillant sauce soja', 'Fécule de maïs', 'Glucides', '3 c. à soupe'),
  ('Tofu croustillant sauce soja', 'Sauce soja', 'Épices & Condiments', '3 c. à soupe'),
  ('Tofu croustillant sauce soja', 'Miel', 'Sucré', '1 c. à soupe'),
  ('Tofu croustillant sauce soja', 'Riz', 'Glucides', '250 g'),
  ('Gratin de courgettes au chèvre', 'Courgette', 'Légumes', '4'),
  ('Gratin de courgettes au chèvre', 'Chèvre', 'Produits Laitiers', '150 g'),
  ('Gratin de courgettes au chèvre', 'Crème soja', 'Produits Laitiers', '20 cl'),
  ('Gratin de courgettes au chèvre', 'Œuf', 'Protéines', '2'),
  ('Gratin de courgettes au chèvre', 'Ail', 'Épices & Condiments', '1 gousse'),
  ('Poivrons farcis au riz', 'Poivron', 'Légumes', '4'),
  ('Poivrons farcis au riz', 'Riz', 'Glucides', '200 g'),
  ('Poivrons farcis au riz', 'Oignon', 'Légumes', '1'),
  ('Poivrons farcis au riz', 'Pulpe de tomate', 'Légumes', '200 g'),
  ('Poivrons farcis au riz', 'Fromage', 'Produits Laitiers', '80 g'),
  ('Curry de patate douce', 'Patate douce', 'Glucides', '800 g'),
  ('Curry de patate douce', 'Lait de coco', 'Produits Laitiers', '40 cl'),
  ('Curry de patate douce', 'Curry', 'Épices & Condiments', '2 c. à café'),
  ('Curry de patate douce', 'Oignon', 'Légumes', '1'),
  ('Curry de patate douce', 'Épinards', 'Légumes', '150 g'),
  ('Crêpes sucrées', 'Farine', 'Glucides', '250 g'),
  ('Crêpes sucrées', 'Œuf', 'Protéines', '3'),
  ('Crêpes sucrées', 'Lait', 'Produits Laitiers', '50 cl'),
  ('Crêpes sucrées', 'Sucre', 'Sucré', '2 c. à soupe'),
  ('Crêpes sucrées', 'Beurre', 'Produits Laitiers', '30 g'),
  ('Gâteau au yaourt', 'Yaourt nature', 'Produits Laitiers', '1'),
  ('Gâteau au yaourt', 'Farine', 'Glucides', '3 pots'),
  ('Gâteau au yaourt', 'Sucre', 'Sucré', '2 pots'),
  ('Gâteau au yaourt', 'Œuf', 'Protéines', '3'),
  ('Gâteau au yaourt', 'Huile', 'Matières Grasses', '1/2 pot'),
  ('Moelleux au chocolat', 'Chocolat noir', 'Sucré', '200 g'),
  ('Moelleux au chocolat', 'Beurre', 'Produits Laitiers', '100 g'),
  ('Moelleux au chocolat', 'Œuf', 'Protéines', '3'),
  ('Moelleux au chocolat', 'Sucre', 'Sucré', '80 g'),
  ('Moelleux au chocolat', 'Farine', 'Glucides', '50 g'),
  ('Compote pomme cannelle', 'Pomme', 'Fruits', '6'),
  ('Compote pomme cannelle', 'Cannelle', 'Épices & Condiments', '1 c. à café'),
  ('Compote pomme cannelle', 'Sucre', 'Sucré', '1 c. à soupe'),
  ('Compote pomme cannelle', 'Citron', 'Fruits', '1/2'),
  ('Riz au lait vanillé', 'Riz', 'Glucides', '150 g'),
  ('Riz au lait vanillé', 'Lait', 'Produits Laitiers', '1 l'),
  ('Riz au lait vanillé', 'Sucre', 'Sucré', '80 g'),
  ('Riz au lait vanillé', 'Vanille', 'Épices & Condiments', '1 gousse'),
  ('Cookies chocolat', 'Farine', 'Glucides', '250 g'),
  ('Cookies chocolat', 'Beurre', 'Produits Laitiers', '120 g'),
  ('Cookies chocolat', 'Sucre', 'Sucré', '120 g'),
  ('Cookies chocolat', 'Œuf', 'Protéines', '1'),
  ('Cookies chocolat', 'Chocolat noir', 'Sucré', '150 g'),
  ('Salade de fruits frais', 'Pomme', 'Fruits', '2'),
  ('Salade de fruits frais', 'Banane', 'Fruits', '2'),
  ('Salade de fruits frais', 'Orange', 'Fruits', '2'),
  ('Salade de fruits frais', 'Fruits rouges', 'Fruits', '150 g'),
  ('Salade de fruits frais', 'Miel', 'Sucré', '1 c. à soupe'),
  ('Salade de fruits frais', 'Citron', 'Fruits', '1'),
  ('Banana bread', 'Banane', 'Fruits', '3'),
  ('Banana bread', 'Farine', 'Glucides', '220 g'),
  ('Banana bread', 'Sucre', 'Sucré', '120 g'),
  ('Banana bread', 'Œuf', 'Protéines', '2'),
  ('Banana bread', 'Beurre', 'Produits Laitiers', '80 g'),
  ('Banana bread', 'Cannelle', 'Épices & Condiments', '1 c. à café')
) as v(title, name, category_name, quantity)
join public.starter_recipes sr on sr.title = v.title
on conflict (starter_recipe_id, name) do update
  set category_name = excluded.category_name, quantity = excluded.quantity;
